apiVersion: v1
kind: Service
metadata:
  name: flask-metrics
  namespace: flask-app
spec:
  selector:
    app.kubernetes.io/name: flask-app
    app.kubernetes.io/instance: {{ .Release.Name }}   # Add this line in Helm template
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
